package com.payflow.authservice.service.impl;

import com.payflow.authservice.exceptions.*;
import com.payflow.authservice.model.entity.User;
import com.payflow.authservice.model.entity.UserCredentials;
import com.payflow.authservice.model.enums.OtpPurpose;
import com.payflow.authservice.model.enums.UserStatus;
import com.payflow.authservice.payload.requestDto.*;
import com.payflow.authservice.payload.responseDto.MessageResponse;
import com.payflow.authservice.payload.responseDto.TokenResponse;
import com.payflow.authservice.repository.UserCredentialRepository;
import com.payflow.authservice.repository.UserRepository;
import com.payflow.authservice.security.service.CustomUserDetails;
import com.payflow.authservice.service.AuthService;
import com.payflow.authservice.service.EmailService;
import com.payflow.authservice.service.OtpService;
import com.payflow.authservice.service.TokenService;
import com.payflow.authservice.utils.UserNameGenerator;
import com.payflow.common.constant.Roles;
import com.payflow.common.exceptions.BusinessException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.authentication.*;
import org.springframework.security.core.Authentication;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.time.temporal.ChronoUnit;

@Slf4j
@RequiredArgsConstructor
@Service
public class AuthServiceImpl  implements AuthService {

     private static final int MAX_FAILED_ATTEMPTS = 5;
     private static final long LOCK_DURATION_HOURS = 24;

     private final UserRepository userRepository;
     private final UserCredentialRepository userCredentialRepository;
     private final PasswordEncoder passwordEncoder;
     private final AuthenticationManager authenticationManager;
     private final OtpService otpService;
     private final EmailService emailService;
     private final TokenService tokenService;
     private final UserNameGenerator userNameGenerator;


    @Override
    public MessageResponse registerUser(RegisterRequest registerRequest) {
         // checking the password and confirm password are equal or not
        if(!registerRequest.getPassword().equals(registerRequest.getConfirmPassword())){
            throw new PasswordMismatchException();
        }

        // Determine username : Provided or auto-generated
        String userName = registerRequest.getUserName();
        boolean isAutoGenerated = false;

        // if username is not provided , then generating new username checking condition that if it
        // already exists or not
        if(userName == null || userName.isBlank()){
            userName = generateUniqueUsername(registerRequest.getEmail());
            isAutoGenerated = true;
        }else{
            if (userRepository.existsByUserName(userName))
                throw new UserNameAlreadyTakenException(userName);
        }

        // checking that user already exits with given email or not
        if(userRepository.existsByEmail(registerRequest.getEmail())){
            throw new EmailAlreadyRegisteredException(registerRequest.getEmail());
        }

        User user = User.builder()
                .userName(userName)
                .email(registerRequest.getEmail())
                .firstName(registerRequest.getFirstName())
                .lastName(registerRequest.getLastName())
                .role(Roles.CUSTOMER)
                .userStatus(UserStatus.PENDING_VERIFICATION)
                .emailVerified(false)
                .failedAttempts(0)
                .userNameChangedAt(isAutoGenerated ? null : Instant.now())
                .userNameReminderCount(0)
                .build();

        userRepository.save(user);

       userCredentialRepository.save(  UserCredentials.builder()
                .user(user)
                .password(passwordEncoder.encode(registerRequest.getPassword()))
                .passwordChangedAt(Instant.now())
                .resetTokenConsumed(true)
                .build());

       // generate and send OTP
        otpService.generateAndSend(registerRequest.getEmail() , OtpPurpose.EMAIL_VERIFICATION);

        if(!isAutoGenerated){
            emailService.sendTemporaryUsernameEmail(registerRequest.getEmail() , userName);
        }

        return new MessageResponse( registerRequest.getFirstName().concat(" " + registerRequest.getLastName()) +
                "registered successfully . with mail : " +registerRequest.getEmail() + " At " +user.getCreatedAt()
         + " with username : " + userName);
    }


    @Override
    public MessageResponse verifyEmail(VerifyEmailRequest emailRequest) {
        User user = userRepository.
                findByEmail(emailRequest.getEmail())
                .orElseThrow(InvalidOtpException::new);

        otpService.verifyOtp(emailRequest.getEmail() , emailRequest.getOtp() , OtpPurpose.EMAIL_VERIFICATION);

        user.setEmailVerified(true);
        user.setUserStatus(UserStatus.ACTIVE);
        userRepository.save(user);

        emailService.sendWelcomeEmail(emailRequest.getEmail() , user.getUserName());

        return new MessageResponse( user.getFirstName().concat(" " + user.getLastName()) +
                " is verified successfully with mail : " +user.getEmail() + " At " +user.getCreatedAt()
                + " with username : " + user.getUserName());
    }

    @Override
    public MessageResponse resendOtp(ResendOtpRequest otpRequest) {
        User user = userRepository.findByEmail(otpRequest.getEmail())
                .orElseThrow(() -> new BusinessException("No account with this email" + otpRequest.getEmail(),
                        "EMAIL_NOT_FOUND"));
        if (Boolean.TRUE.equals(user.getEmailVerified())){
            throw new BusinessException("Email Already Verified" , "EMAIL_ALREADY_VERIFIED");
        }

        otpService.generateAndSend(otpRequest.getEmail() , OtpPurpose.EMAIL_VERIFICATION);

        return new MessageResponse(user.getFirstName().concat(" " + user.getLastName()) +
                " Otp sent successfully with mail : " +user.getEmail()
                + " with username : " + user.getUserName());
    }

    @Override
    public TokenResponse login(LoginRequest loginRequest) {
        Authentication auth;
        User user = userRepository.
                findByUsernameOrEmail(loginRequest.getIdentifier()).orElseThrow(
                        () -> new BusinessException("No account with this identifier" + loginRequest.getIdentifier(),
                                "IDENTIFIER_NOT_FOUND")
                );
        try{
            auth = authenticationManager.authenticate(
                    new UsernamePasswordAuthenticationToken(
                            loginRequest.getIdentifier(),
                            loginRequest.getPassword()
                    ));
        }catch (LockedException e){
            String until = user.getLockedUntil() != null
                    ? user.getLockedUntil().toString() : "Unknown";
            throw new BusinessException("Account is locked until " + until , "ACCOUNT_LOCKED");
        }catch (DisabledException e){
           if(!Boolean.TRUE.equals(user.getEmailVerified())){
               throw new BusinessException("Email is Not Verified , Please verify first. " , "EMAIL_NOT_VERIFIED");
           }
           throw new BusinessException("Account is Not Active" , "ACCOUNT_NOT_ACTIVE");
        }catch (BadCredentialsException e){
              handleFailedLogin(user);
              throw new InvalidCredentialsException();
          }

            CustomUserDetails details = (CustomUserDetails) auth.getPrincipal();
            assert details != null;
             User  user1 =details.getUser();

            user1.setFailedAttempts(0);
            user1.setLockedUntil(null);
            user1.setLastLoginAt(Instant.now());
            userRepository.save(user1);


        return tokenService.issueTokens(user1);
    }

    @Override
    public TokenResponse refreshToken(RefreshTokenRequest refreshToken) {

        return tokenService.refreshTokens(refreshToken.getRefreshToken());
    }

    @Override
    public MessageResponse logout(Long userId) {
       tokenService.revokeAllForUser(userId , "Logout");
       return new MessageResponse("Logout successful");
    }

    @Override
    public MessageResponse changePassword(Long userId, ChangePasswordRequest changePasswordRequest) {
        if (!changePasswordRequest.getNewPassword().
                equals(changePasswordRequest.getConfirmNewPassword())){
            throw new PasswordMismatchException();
        }

        UserCredentials userCredentials = userCredentialRepository.findByUserId(userId)
                .orElseThrow(() -> new BusinessException("Credentials not found", "CREDENTIALS_NOT_FOUND"));

        if (!passwordEncoder.matches(changePasswordRequest.getCurrentPassword() , userCredentials.getPassword())){
            throw new BusinessException("Current password is incorrect", "INVALID_CURRENT_PASSWORD");
        }

        userCredentials.setPassword(passwordEncoder.encode(changePasswordRequest.getNewPassword()));
        userCredentials.setPasswordChangedAt(Instant.now());
        userCredentialRepository.save(userCredentials);

        return new MessageResponse("Password changed successfully with user Id" + userId);
    }


    @Override
    public MessageResponse forgotPassword(ForgetPasswordRequest forgotPasswordRequest) {
        userRepository.findByEmail(forgotPasswordRequest.getEmail()).ifPresent(
                user -> {
                    otpService.generateAndSend(forgotPasswordRequest.getEmail(), OtpPurpose.PASSWORD_RESET);
                }
        );
        return new MessageResponse("OTP sent successfully with email : " + forgotPasswordRequest.getEmail());
    }

    @Override
    public MessageResponse resetPassword(ResetPasswordRequest resetPasswordRequest) {
        if (!resetPasswordRequest.getNewPassword().equals(resetPasswordRequest.getConfirmNewPassword())){
            throw new PasswordMismatchException();
        }

        User user = userRepository.findByEmail(resetPasswordRequest.getEmail()).orElseThrow(
                InvalidOtpException::new
        );

        otpService.verifyOtp(resetPasswordRequest.getEmail() , resetPasswordRequest.getOtp() , OtpPurpose.PASSWORD_RESET );

        UserCredentials credential = userCredentialRepository.findByUserId(user.getId())
                .orElseThrow(() -> new BusinessException("Credentials not found", "CREDENTIALS_NOT_FOUND"));

        credential.setPassword(passwordEncoder.encode(resetPasswordRequest.getNewPassword()));
        credential.setPasswordChangedAt(Instant.now());
        userCredentialRepository.save(credential);

        user.setFailedAttempts(0);
        user.setLockedUntil(null);
        userRepository.save(user);
        return new MessageResponse("Password reset successfully. You can now log in.");
    }

    private void handleFailedLogin(User user){
        int attempts = user.getFailedAttempts() + 1;
        user.setFailedAttempts(attempts);
        if(attempts >= MAX_FAILED_ATTEMPTS){
            user.setLockedUntil(Instant.now().plus(LOCK_DURATION_HOURS , ChronoUnit.HOURS));
        }
        userRepository.save(user);

    }

    private String generateUniqueUsername(String email) {
        for (int i = 0; i < 10; i++) {
            String candidate = userNameGenerator.generateFromEmail(email);
            if (!userRepository.existsByUserName(candidate)) {
                return candidate;
            }
        }
        throw new IllegalStateException("Failed to generate unique username after 10 attempts");
    }
}
