package com.payflow.common.audit;

public enum AuditEventType {
    // ────────────────  AUTH / IDENTITY  ────────────────
    USER_REGISTERED,
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    EMAIL_VERIFIED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    ACCOUNT_SUSPENDED,
    REFRESH_TOKEN_REVOKED,
    REFRESH_TOKEN_THEFT_DETECTED,

    // ────────────────  MERCHANT  ────────────────
    MERCHANT_CREATED,
    MERCHANT_APPROVED,
    MERCHANT_REJECTED,
    MERCHANT_SUSPENDED,
    MERCHANT_GATEWAY_KEY_ADDED,
    MERCHANT_GATEWAY_KEY_REVOKED,
    MERCHANT_KYC_SUBMITTED,
    MERCHANT_KYC_VERIFIED,

    // ────────────────  PAYMENT  ────────────────
    PAYMENT_INITIATED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    PAYMENT_REFUND_FAILED,
    PAYMENT_DUPLICATE_DETECTED,

    // ────────────────  LEDGER  ────────────────
    LEDGER_ENTRY_CREATED,
    LEDGER_WRITE_FAILED,
    LEDGER_CORRUPTION_DETECTED,

    // ────────────────  RECONCILIATION  ────────────────
    RECONCILIATION_RUN_STARTED,
    RECONCILIATION_RUN_COMPLETED,
    RECONCILIATION_MISMATCH_FOUND,
    RECONCILIATION_MISMATCH_RESOLVED,
    SETTLEMENT_APPROVED,

    // ────────────────  FILE  ────────────────
    FILE_UPLOADED,
    FILE_DELETED,
    FILE_ACCESS_DENIED,

    // ────────────────  ADMIN  ────────────────
    ADMIN_ACTION_PERFORMED,
    CONFIG_CHANGED
}